### ISSUE TITLE
GitHub Issues

### ISSUE THREAD

**Issue by mcordell** [MonkDev/monk-conventions#5]
At the moment we do not have a formalized methodology for creating, handling, or escalating issues in github. This problem decreases the likelihood that bugs will be handled and ease with which they are handled. I would like to propose we formalize this procedure.

**Comment by jstayton** [comment]
I agree with almost all of this, but I'd like to wait until we have a full-time Support Engineer (a.k.a, Chris) so he can really own this and set the final conventions. Closing until then.
